version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: primetrade_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: primetrade_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - primetrade_network

  app:
    build: .
    container_name: primetrade_app
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/primetrade_db?schema=public
      JWT_SECRET: super-secret-key
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run dev"
    networks:
      - primetrade_network

volumes:
  postgres_data:

networks:
  primetrade_network:
    driver: bridge
